[package]
edition = "2021"
name = "timv"
version = "0.2.0"
description = "Terminal image viewer"
authors = ["Ismaïl Senhaji <ismail.senhaji@gmail.com>"]

[dependencies]
clap = "3.1"
image = "0.24"
itertools = "0.10"
termion = "1.5"
